// 'use client';
import {getKindeServerSession} from "@kinde-oss/kinde-auth-nextjs/server";
import { Inter } from "next/font/google";
import "./globals.css";
import Provider from "./Provider";
import {ContentProvider} from "./contexts/ContentContext";
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Initiator",
  description: "Generated by create next app",
  charset: "UTF-8",
  openGraph: {
    title: "Initiator",
    description: "Generated by create next app",
    url: "https://yourwebsite.com",
    siteName: "Your Site Name",
    // images: [
    //   {
    //     url: "https://yourwebsite.com/image.jpg",
    //     width: 800,
    //     height: 600,
    //     alt: "Image description",
    //   },
    // ],
    locale: "en_US",
    type: "website",
  },
  // twitter: {
  //   card: "summary_large_image",
  //   title: "Clinic",
  //   description: "Generated by create next app",
  //   site: "@yourtwitterhandle",
  //   creator: "@yourtwitterhandle",
  //   image: "https://yourwebsite.com/image.jpg",
  // }
};

export const viewport = {
  width: "device-width",
  initialScale: 1.0,
};

export default async function RootLayout({ children
  // , session
 }) {
  let User={};
  const {getUser} = getKindeServerSession();
  User = await getUser();

console.log('userLayout',User);
  return (
    <html lang="en">
      <body className={inter.className}>
        <ContentProvider
         User={User}
         >
          <Provider>{children}</Provider>
        </ContentProvider>
      </body>
    </html>
  );
}
